title: Mikko Nurminen
description: > 
  Researcher in health economics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
email: mikko.nurminen@kela.fi
linkedin: mikko-nurminen
twitter: NurminenMikko
github:  mikkonurminen
goodreads: mikkonurminen

# Build settings
markdown: kramdown
encoding: utf-8
plugins:

sass:
    style: compressed
    sass_dir: _sass

include: ['_pages']
